<?php
/**
 * GENERATED by bin/palette-build.php from bin/palette-sources.json. DO NOT EDIT BY HAND.
 *
 * @package EliteAutoDealer
 */

return array (
  'aurelis' => 
  array (
    'name' => 'Aurelis',
    'default' => true,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#121316',
      1 => '#2b2e33',
      2 => '#a88a55',
      3 => '#d2bd94',
      4 => '#f5f3ee',
    ),
    'slots' => 
    array (
      'ink' => '#121316',
      'graphite' => '#1c1e22',
      'graphite-2' => '#2b2e33',
      'paper' => '#f5f3ee',
      'paper-2' => '#ebe7de',
      'surface' => '#ffffff',
      'line' => '#dfdad0',
      'text' => '#16171a',
      'muted' => '#5d5f64',
      'muted-light' => '#b8bbc1',
      'accent' => '#a88a55',
      'accent-light' => '#d2bd94',
      'accent-ink' => '#786441',
      'on-accent' => '#121316',
      'field-line' => '#878480',
      'accent-card' => '#9c8050',
      'accent-muted' => '#1e1d1b',
      'accent-focus' => '#121316',
      'accent-hover' => '#29251f',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.32)',
      1 => 'field-line: line darkened to a field boundary (push 0.44)',
    ),
  ),
  'carbon-prestige' => 
  array (
    'name' => 'Carbon Prestige',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#101011',
      1 => '#2a2b2d',
      2 => '#c9cdd2',
      3 => '#dcdee2',
      4 => '#f3f3f4',
    ),
    'slots' => 
    array (
      'ink' => '#101011',
      'graphite' => '#1c1d1e',
      'graphite-2' => '#2a2b2d',
      'paper' => '#f3f3f4',
      'paper-2' => '#e4e4e5',
      'surface' => '#ffffff',
      'line' => '#d5d5d6',
      'text' => '#161718',
      'muted' => '#616366',
      'muted-light' => '#b1b2b4',
      'accent' => '#c9cdd2',
      'accent-light' => '#dcdee2',
      'accent-ink' => '#616366',
      'on-accent' => '#101011',
      'field-line' => '#7d7e7f',
      'accent-card' => '#babec3',
      'accent-muted' => '#47494b',
      'accent-focus' => '#101011',
      'accent-hover' => '#2c2c2e',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.56)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'midnight-titanium' => 
  array (
    'name' => 'Midnight Titanium',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0c0e16',
      1 => '#212636',
      2 => '#a59f92',
      3 => '#c4c1b8',
      4 => '#f4f4f3',
    ),
    'slots' => 
    array (
      'ink' => '#0c0e16',
      'graphite' => '#151925',
      'graphite-2' => '#212636',
      'paper' => '#f4f4f3',
      'paper-2' => '#e6e5e3',
      'surface' => '#ffffff',
      'line' => '#d8d6d3',
      'text' => '#10131e',
      'muted' => '#59627d',
      'muted-light' => '#a8adbd',
      'accent' => '#a59f92',
      'accent-light' => '#c4c1b8',
      'accent-ink' => '#65625e',
      'on-accent' => '#0c0e16',
      'field-line' => '#7c7c80',
      'accent-card' => '#999388',
      'accent-muted' => '#28282c',
      'accent-focus' => '#0c0e16',
      'accent-hover' => '#232429',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.42)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'gunmetal' => 
  array (
    'name' => 'Gunmetal',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0f1113',
      1 => '#272c30',
      2 => '#4a6363',
      3 => '#899a9a',
      4 => '#f3f4f4',
    ),
    'slots' => 
    array (
      'ink' => '#0f1113',
      'graphite' => '#1a1e20',
      'graphite-2' => '#272c30',
      'paper' => '#f3f4f4',
      'paper-2' => '#e2e5e6',
      'surface' => '#ffffff',
      'line' => '#d2d6d9',
      'text' => '#14171a',
      'muted' => '#5b6267',
      'muted-light' => '#aeb3b7',
      'accent' => '#4a6363',
      'accent-light' => '#899a9a',
      'accent-ink' => '#4a6363',
      'on-accent' => '#ffffff',
      'field-line' => '#7b7e81',
      'accent-card' => '#586f6f',
      'accent-muted' => '#f1f3f3',
      'accent-focus' => '#ffffff',
      'accent-hover' => '#e4e8e8',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'obsidian-gold' => 
  array (
    'name' => 'Obsidian Gold',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#14110e',
      1 => '#322d25',
      2 => '#c9a23a',
      3 => '#dcc37f',
      4 => '#f7f4f0',
    ),
    'slots' => 
    array (
      'ink' => '#14110e',
      'graphite' => '#221f19',
      'graphite-2' => '#322d25',
      'paper' => '#f7f4f0',
      'paper-2' => '#ece6dc',
      'surface' => '#fdfcfb',
      'line' => '#e2d9c9',
      'text' => '#1b1813',
      'muted' => '#6a6357',
      'muted-light' => '#b9b4ac',
      'accent' => '#c9a23a',
      'accent-light' => '#dcc37f',
      'accent-ink' => '#796227',
      'on-accent' => '#14110e',
      'field-line' => '#827c72',
      'accent-card' => '#bb9636',
      'accent-muted' => '#382e17',
      'accent-focus' => '#14110e',
      'accent-hover' => '#2f2715',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.44)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'volcanic-ash' => 
  array (
    'name' => 'Volcanic Ash',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#12100f',
      1 => '#2f2a28',
      2 => '#9e2b1f',
      3 => '#c98882',
      4 => '#f4f2f1',
    ),
    'slots' => 
    array (
      'ink' => '#12100f',
      'graphite' => '#201c1b',
      'graphite-2' => '#2f2a28',
      'paper' => '#f4f2f1',
      'paper-2' => '#e5e1df',
      'surface' => '#ffffff',
      'line' => '#d9d3d0',
      'text' => '#191615',
      'muted' => '#665f5c',
      'muted-light' => '#b6b1af',
      'accent' => '#9e2b1f',
      'accent-light' => '#c98882',
      'accent-ink' => '#9e2b1f',
      'on-accent' => '#ffffff',
      'field-line' => '#7d7876',
      'accent-card' => '#a63c31',
      'accent-muted' => '#efdddb',
      'accent-focus' => '#ffffff',
      'accent-hover' => '#f0dfdd',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'onyx-ivory' => 
  array (
    'name' => 'Onyx Ivory',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#11100e',
      1 => '#2d2b27',
      2 => '#e3d6bb',
      3 => '#ede4d3',
      4 => '#f8f4ef',
    ),
    'slots' => 
    array (
      'ink' => '#11100e',
      'graphite' => '#1e1c1a',
      'graphite-2' => '#2d2b27',
      'paper' => '#f8f4ef',
      'paper-2' => '#efe6da',
      'surface' => '#fefcfa',
      'line' => '#e6d8c5',
      'text' => '#171614',
      'muted' => '#68645f',
      'muted-light' => '#b5b3b0',
      'accent' => '#e3d6bb',
      'accent-light' => '#ede4d3',
      'accent-ink' => '#696357',
      'on-accent' => '#11100e',
      'field-line' => '#837b70',
      'accent-card' => '#d2c6ad',
      'accent-muted' => '#544f45',
      'accent-focus' => '#11100e',
      'accent-hover' => '#312e28',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.58)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'shadow-line' => 
  array (
    'name' => 'Shadow Line',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0b0d0e',
      1 => '#212327',
      2 => '#363a3f',
      3 => '#8e9193',
      4 => '#f3f3f4',
    ),
    'slots' => 
    array (
      'ink' => '#0b0d0e',
      'graphite' => '#151719',
      'graphite-2' => '#212327',
      'paper' => '#f3f3f4',
      'paper-2' => '#e3e4e5',
      'surface' => '#ffffff',
      'line' => '#d4d5d7',
      'text' => '#111315',
      'muted' => '#5e6369',
      'muted-light' => '#afb2b6',
      'accent' => '#363a3f',
      'accent-light' => '#8e9193',
      'accent-ink' => '#363a3f',
      'on-accent' => '#ffffff',
      'field-line' => '#7a7c7e',
      'accent-card' => '#464a4e',
      'accent-muted' => '#bbbcbe',
      'accent-focus' => '#ffffff',
      'accent-hover' => '#e1e1e2',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'satin-steel' => 
  array (
    'name' => 'Satin Steel',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0e1113',
      1 => '#262c31',
      2 => '#8299ac',
      3 => '#aebdc9',
      4 => '#f2f4f5',
    ),
    'slots' => 
    array (
      'ink' => '#0e1113',
      'graphite' => '#191e22',
      'graphite-2' => '#262c31',
      'paper' => '#f2f4f5',
      'paper-2' => '#e2e4e7',
      'surface' => '#ffffff',
      'line' => '#d1d6da',
      'text' => '#13171b',
      'muted' => '#5b646c',
      'muted-light' => '#adb3b8',
      'accent' => '#8299ac',
      'accent-light' => '#aebdc9',
      'accent-ink' => '#566572',
      'on-accent' => '#0e1113',
      'field-line' => '#7a7e82',
      'accent-card' => '#798ea0',
      'accent-muted' => '#1c2125',
      'accent-focus' => '#0e1113',
      'accent-hover' => '#1f252a',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.38)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'monaco-blue' => 
  array (
    'name' => 'Monaco Blue',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#080d19',
      1 => '#1a243d',
      2 => '#2f5bb7',
      3 => '#7894d0',
      4 => '#f1f3f6',
    ),
    'slots' => 
    array (
      'ink' => '#080d19',
      'graphite' => '#10182b',
      'graphite-2' => '#1a243d',
      'paper' => '#f1f3f6',
      'paper-2' => '#dee2ea',
      'surface' => '#fbfcfd',
      'line' => '#ccd2df',
      'text' => '#0b1222',
      'muted' => '#4e5f89',
      'muted-light' => '#a1acc4',
      'accent' => '#2f5bb7',
      'accent-light' => '#7894d0',
      'accent-ink' => '#2f5bb7',
      'on-accent' => '#fbfcfd',
      'field-line' => '#737a88',
      'accent-card' => '#3f68bd',
      'accent-muted' => '#eff2f9',
      'accent-focus' => '#fbfcfd',
      'accent-hover' => '#dce4f3',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'navy-heritage' => 
  array (
    'name' => 'Navy Heritage',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#070e1a',
      1 => '#18263e',
      2 => '#b4413c',
      3 => '#ce8480',
      4 => '#f7f5f0',
    ),
    'slots' => 
    array (
      'ink' => '#070e1a',
      'graphite' => '#0f192c',
      'graphite-2' => '#18263e',
      'paper' => '#f7f5f0',
      'paper-2' => '#ece7dc',
      'surface' => '#fdfcfb',
      'line' => '#e2dbc9',
      'text' => '#0a1424',
      'muted' => '#4c658f',
      'muted-light' => '#a0adc5',
      'accent' => '#b4413c',
      'accent-light' => '#ce8480',
      'accent-ink' => '#ad3f3b',
      'on-accent' => '#fdfcfb',
      'field-line' => '#7f7f7d',
      'accent-card' => '#ba504b',
      'accent-muted' => '#fdfcfb',
      'accent-focus' => '#070e1a',
      'accent-hover' => '#f6e9e8',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.04)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'glacier-blue' => 
  array (
    'name' => 'Glacier Blue',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0b1217',
      1 => '#1f2d38',
      2 => '#8cc4dc',
      3 => '#b4d9e8',
      4 => '#f3f7fa',
    ),
    'slots' => 
    array (
      'ink' => '#0b1217',
      'graphite' => '#141f27',
      'graphite-2' => '#1f2d38',
      'paper' => '#f3f7fa',
      'paper-2' => '#e1ebf2',
      'surface' => '#fafcfe',
      'line' => '#c9dbe8',
      'text' => '#0f181f',
      'muted' => '#52697a',
      'muted-light' => '#a6b5bf',
      'accent' => '#8cc4dc',
      'accent-light' => '#b4d9e8',
      'accent-ink' => '#4c6b7a',
      'on-accent' => '#0b1217',
      'field-line' => '#73818c',
      'accent-card' => '#82b6cc',
      'accent-muted' => '#2d404a',
      'accent-focus' => '#0b1217',
      'accent-hover' => '#1e2d35',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.50)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'estoril-blue' => 
  array (
    'name' => 'Estoril Blue',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0d1014',
      1 => '#242a32',
      2 => '#4ea1ff',
      3 => '#8cc2ff',
      4 => '#f2f3f5',
    ),
    'slots' => 
    array (
      'ink' => '#0d1014',
      'graphite' => '#181d23',
      'graphite-2' => '#242a32',
      'paper' => '#f2f3f5',
      'paper-2' => '#e2e4e7',
      'surface' => '#ffffff',
      'line' => '#d1d5da',
      'text' => '#12161c',
      'muted' => '#59626e',
      'muted-light' => '#acb2b9',
      'accent' => '#4ea1ff',
      'accent-light' => '#8cc2ff',
      'accent-ink' => '#33649c',
      'on-accent' => '#0d1014',
      'field-line' => '#797d83',
      'accent-card' => '#4995ec',
      'accent-muted' => '#192a3e',
      'accent-focus' => '#0d1014',
      'accent-hover' => '#172637',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.42)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'storm-blue' => 
  array (
    'name' => 'Storm Blue',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0c1116',
      1 => '#212b36',
      2 => '#456785',
      3 => '#869cb0',
      4 => '#f0f2f4',
    ),
    'slots' => 
    array (
      'ink' => '#0c1116',
      'graphite' => '#151d25',
      'graphite-2' => '#212b36',
      'paper' => '#f0f2f4',
      'paper-2' => '#dde2e6',
      'surface' => '#fbfcfd',
      'line' => '#cdd4db',
      'text' => '#10171e',
      'muted' => '#536374',
      'muted-light' => '#a8b2bd',
      'accent' => '#456785',
      'accent-light' => '#869cb0',
      'accent-ink' => '#436481',
      'on-accent' => '#fbfcfd',
      'field-line' => '#727980',
      'accent-card' => '#54738f',
      'accent-muted' => '#f7f9fb',
      'accent-focus' => '#fbfcfd',
      'accent-hover' => '#e0e6eb',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.04)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'riviera-blue' => 
  array (
    'name' => 'Riviera Blue',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#080f19',
      1 => '#1a283d',
      2 => '#348ece',
      3 => '#7bb6df',
      4 => '#f8f5ef',
    ),
    'slots' => 
    array (
      'ink' => '#080f19',
      'graphite' => '#101b2b',
      'graphite-2' => '#1a283d',
      'paper' => '#f8f5ef',
      'paper-2' => '#efe7da',
      'surface' => '#fefcfa',
      'line' => '#e6dac5',
      'text' => '#0b1522',
      'muted' => '#4e6689',
      'muted-light' => '#a1b0c4',
      'accent' => '#348ece',
      'accent-light' => '#7bb6df',
      'accent-ink' => '#286a9b',
      'on-accent' => '#080f19',
      'field-line' => '#817f7a',
      'accent-card' => '#3084c0',
      'accent-muted' => '#080f19',
      'accent-focus' => '#080f19',
      'accent-hover' => '#0d1e2f',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.28)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'british-racing' => 
  array (
    'name' => 'British Racing',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#091811',
      1 => '#1c3b2c',
      2 => '#2e6a4e',
      3 => '#8aac9c',
      4 => '#f7f5f0',
    ),
    'slots' => 
    array (
      'ink' => '#091811',
      'graphite' => '#11291e',
      'graphite-2' => '#1c3b2c',
      'paper' => '#f7f5f0',
      'paper-2' => '#ede9db',
      'surface' => '#fefdfa',
      'line' => '#e4ddc7',
      'text' => '#0d2118',
      'muted' => '#436f5b',
      'muted-light' => '#a3c2b4',
      'accent' => '#2e6a4e',
      'accent-light' => '#8aac9c',
      'accent-ink' => '#2e6a4e',
      'on-accent' => '#fefdfa',
      'field-line' => '#7d8373',
      'accent-card' => '#3f765c',
      'accent-muted' => '#f2f4f0',
      'accent-focus' => '#fefdfa',
      'accent-hover' => '#dfe7e0',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'petrol' => 
  array (
    'name' => 'Petrol',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#081619',
      1 => '#1a373d',
      2 => '#1d6c78',
      3 => '#7aa8af',
      4 => '#f1f5f6',
    ),
    'slots' => 
    array (
      'ink' => '#081619',
      'graphite' => '#10262b',
      'graphite-2' => '#1a373d',
      'paper' => '#f1f5f6',
      'paper-2' => '#dfe8ea',
      'surface' => '#fbfdfd',
      'line' => '#cddbde',
      'text' => '#0b1f22',
      'muted' => '#416a72',
      'muted-light' => '#a1bec4',
      'accent' => '#1d6c78',
      'accent-light' => '#7aa8af',
      'accent-ink' => '#1d6c78',
      'on-accent' => '#fbfdfd',
      'field-line' => '#708184',
      'accent-card' => '#2f7883',
      'accent-muted' => '#f7fafa',
      'accent-focus' => '#fbfdfd',
      'accent-hover' => '#dae7e9',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'alpine-teal' => 
  array (
    'name' => 'Alpine Teal',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0c1415',
      1 => '#223334',
      2 => '#2ab3a6',
      3 => '#75cec5',
      4 => '#f4f8f8',
    ),
    'slots' => 
    array (
      'ink' => '#0c1415',
      'graphite' => '#162324',
      'graphite-2' => '#223334',
      'paper' => '#f4f8f8',
      'paper-2' => '#e3eced',
      'surface' => '#fbfdfd',
      'line' => '#d0dedf',
      'text' => '#111c1d',
      'muted' => '#516a6c',
      'muted-light' => '#aababb',
      'accent' => '#2ab3a6',
      'accent-light' => '#75cec5',
      'accent-ink' => '#1d7069',
      'on-accent' => '#0c1415',
      'field-line' => '#748182',
      'accent-card' => '#28a69a',
      'accent-muted' => '#112d2c',
      'accent-focus' => '#0c1415',
      'accent-hover' => '#112c2b',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.42)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'moss-grey' => 
  array (
    'name' => 'Moss Grey',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#10140e',
      1 => '#2a3225',
      2 => '#8a9a5b',
      3 => '#b3bd94',
      4 => '#f6f6f1',
    ),
    'slots' => 
    array (
      'ink' => '#10140e',
      'graphite' => '#1d2219',
      'graphite-2' => '#2a3225',
      'paper' => '#f6f6f1',
      'paper-2' => '#eaeadf',
      'surface' => '#fdfdfb',
      'line' => '#dedecd',
      'text' => '#161b13',
      'muted' => '#5f6a57',
      'muted-light' => '#b1b9ac',
      'accent' => '#8a9a5b',
      'accent-light' => '#b3bd94',
      'accent-ink' => '#5e6a3f',
      'on-accent' => '#10140e',
      'field-line' => '#7e8074',
      'accent-card' => '#808f55',
      'accent-muted' => '#1a1f14',
      'accent-focus' => '#10140e',
      'accent-hover' => '#22281a',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.36)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'emerald-touring' => 
  array (
    'name' => 'Emerald Touring',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0b1612',
      1 => '#20362f',
      2 => '#20a16d',
      3 => '#6ec2a0',
      4 => '#f2f5f4',
    ),
    'slots' => 
    array (
      'ink' => '#0b1612',
      'graphite' => '#152620',
      'graphite-2' => '#20362f',
      'paper' => '#f2f5f4',
      'paper-2' => '#e0e8e5',
      'surface' => '#ffffff',
      'line' => '#d0dbd7',
      'text' => '#101e19',
      'muted' => '#4a695e',
      'muted-light' => '#a7beb6',
      'accent' => '#20a16d',
      'accent-light' => '#6ec2a0',
      'accent-ink' => '#19724e',
      'on-accent' => '#0b1612',
      'field-line' => '#74807c',
      'accent-card' => '#1e9666',
      'accent-muted' => '#0c1c16',
      'accent-focus' => '#0b1612',
      'accent-hover' => '#0e291f',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.34)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'saddle-tan' => 
  array (
    'name' => 'Saddle Tan',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#16100b',
      1 => '#362b20',
      2 => '#c49464',
      3 => '#d9b99a',
      4 => '#f8f3ef',
    ),
    'slots' => 
    array (
      'ink' => '#16100b',
      'graphite' => '#261d15',
      'graphite-2' => '#362b20',
      'paper' => '#f8f3ef',
      'paper-2' => '#efe4da',
      'surface' => '#fefcfa',
      'line' => '#e6d4c5',
      'text' => '#1e1610',
      'muted' => '#726050',
      'muted-light' => '#beb2a7',
      'accent' => '#c49464',
      'accent-light' => '#d9b99a',
      'accent-ink' => '#7b5d3f',
      'on-accent' => '#16100b',
      'field-line' => '#86796e',
      'accent-card' => '#b6895d',
      'accent-muted' => '#322519',
      'accent-focus' => '#16100b',
      'accent-hover' => '#302418',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.42)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'espresso-cognac' => 
  array (
    'name' => 'Espresso Cognac',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#150e09',
      1 => '#36261c',
      2 => '#8a4b25',
      3 => '#b68f78',
      4 => '#f7f3f0',
    ),
    'slots' => 
    array (
      'ink' => '#150e09',
      'graphite' => '#241911',
      'graphite-2' => '#36261c',
      'paper' => '#f7f3f0',
      'paper-2' => '#ede2db',
      'surface' => '#fefcfa',
      'line' => '#e4d3c7',
      'text' => '#1e140d',
      'muted' => '#765d4c',
      'muted-light' => '#c0b0a5',
      'accent' => '#8a4b25',
      'accent-light' => '#b68f78',
      'accent-ink' => '#8a4b25',
      'on-accent' => '#fefcfa',
      'field-line' => '#897b71',
      'accent-card' => '#935936',
      'accent-muted' => '#f2eae5',
      'accent-focus' => '#fefcfa',
      'accent-hover' => '#ede1da',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'desert-sand' => 
  array (
    'name' => 'Desert Sand',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#13110f',
      1 => '#302c27',
      2 => '#c9b28a',
      3 => '#dccdb3',
      4 => '#f8f4f0',
    ),
    'slots' => 
    array (
      'ink' => '#13110f',
      'graphite' => '#201e1a',
      'graphite-2' => '#302c27',
      'paper' => '#f8f4f0',
      'paper-2' => '#eee7dd',
      'surface' => '#fefcfa',
      'line' => '#e4d9c8',
      'text' => '#1a1714',
      'muted' => '#6a655d',
      'muted-light' => '#b7b3ae',
      'accent' => '#c9b28a',
      'accent-light' => '#dccdb3',
      'accent-ink' => '#6e624d',
      'on-accent' => '#13110f',
      'field-line' => '#837c72',
      'accent-card' => '#baa580',
      'accent-muted' => '#3f382d',
      'accent-focus' => '#13110f',
      'accent-hover' => '#2e2921',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.50)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'havana' => 
  array (
    'name' => 'Havana',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#15110c',
      1 => '#352b22',
      2 => '#7c5a3c',
      3 => '#aa9480',
      4 => '#f6f2ee',
    ),
    'slots' => 
    array (
      'ink' => '#15110c',
      'graphite' => '#251d16',
      'graphite-2' => '#352b22',
      'paper' => '#f6f2ee',
      'paper-2' => '#eae2d9',
      'surface' => '#fdfcfb',
      'line' => '#e1d4c7',
      'text' => '#1d1711',
      'muted' => '#6d5e50',
      'muted-light' => '#bcb2a9',
      'accent' => '#7c5a3c',
      'accent-light' => '#aa9480',
      'accent-ink' => '#7c5a3c',
      'on-accent' => '#fdfcfb',
      'field-line' => '#837970',
      'accent-card' => '#86674b',
      'accent-muted' => '#f8f6f3',
      'accent-focus' => '#fdfcfb',
      'accent-hover' => '#eae4de',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'dune' => 
  array (
    'name' => 'Dune',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#13120e',
      1 => '#312f26',
      2 => '#a59a6a',
      3 => '#c4bd9e',
      4 => '#f7f6f0',
    ),
    'slots' => 
    array (
      'ink' => '#13120e',
      'graphite' => '#222019',
      'graphite-2' => '#312f26',
      'paper' => '#f7f6f0',
      'paper-2' => '#eceadc',
      'surface' => '#fdfdfb',
      'line' => '#e2dec9',
      'text' => '#1b1913',
      'muted' => '#696758',
      'muted-light' => '#b8b6ad',
      'accent' => '#a59a6a',
      'accent-light' => '#c4bd9e',
      'accent-ink' => '#6e6647',
      'on-accent' => '#13120e',
      'field-line' => '#827f72',
      'accent-card' => '#998f63',
      'accent-muted' => '#27251b',
      'accent-focus' => '#13120e',
      'accent-hover' => '#29261c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.38)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'oxblood' => 
  array (
    'name' => 'Oxblood',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#180a0b',
      1 => '#3a1d1f',
      2 => '#6e1f2a',
      3 => '#b2888e',
      4 => '#f7f4f0',
    ),
    'slots' => 
    array (
      'ink' => '#180a0b',
      'graphite' => '#281214',
      'graphite-2' => '#3a1d1f',
      'paper' => '#f7f4f0',
      'paper-2' => '#ece4dc',
      'surface' => '#fdfcfb',
      'line' => '#e2d6c9',
      'text' => '#210d0f',
      'muted' => '#875459',
      'muted-light' => '#c1a4a6',
      'accent' => '#6e1f2a',
      'accent-light' => '#b2888e',
      'accent-ink' => '#6e1f2a',
      'on-accent' => '#fdfcfb',
      'field-line' => '#897a73',
      'accent-card' => '#79313b',
      'accent-muted' => '#cfb5b8',
      'accent-focus' => '#fdfcfb',
      'accent-hover' => '#e8dbdc',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'signal-red' => 
  array (
    'name' => 'Signal Red',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#101012',
      1 => '#292b2d',
      2 => '#c8102e',
      3 => '#e0798a',
      4 => '#f3f3f4',
    ),
    'slots' => 
    array (
      'ink' => '#101012',
      'graphite' => '#1c1d1f',
      'graphite-2' => '#292b2d',
      'paper' => '#f3f3f4',
      'paper-2' => '#e3e4e5',
      'surface' => '#ffffff',
      'line' => '#d4d5d7',
      'text' => '#161618',
      'muted' => '#606267',
      'muted-light' => '#b0b2b5',
      'accent' => '#c8102e',
      'accent-light' => '#e0798a',
      'accent-ink' => '#c4102d',
      'on-accent' => '#ffffff',
      'field-line' => '#7d7d7f',
      'accent-card' => '#cc233f',
      'accent-muted' => '#fbecee',
      'accent-focus' => '#101012',
      'accent-hover' => '#f8e2e6',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.02)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'copper-touring' => 
  array (
    'name' => 'Copper Touring',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#13100e',
      1 => '#312a26',
      2 => '#c97b4b',
      3 => '#dca98a',
      4 => '#f6f3f1',
    ),
    'slots' => 
    array (
      'ink' => '#13100e',
      'graphite' => '#221c19',
      'graphite-2' => '#312a26',
      'paper' => '#f6f3f1',
      'paper-2' => '#e9e3df',
      'surface' => '#fdfcfb',
      'line' => '#ddd3ce',
      'text' => '#1b1613',
      'muted' => '#6c615b',
      'muted-light' => '#b8b1ad',
      'accent' => '#c97b4b',
      'accent-light' => '#dca98a',
      'accent-ink' => '#8b5736',
      'on-accent' => '#13100e',
      'field-line' => '#847c78',
      'accent-card' => '#ba7246',
      'accent-muted' => '#1e1612',
      'accent-focus' => '#13100e',
      'accent-hover' => '#2e2017',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.34)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'bordeaux' => 
  array (
    'name' => 'Bordeaux',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#150c0f',
      1 => '#342228',
      2 => '#8e2445',
      3 => '#c08497',
      4 => '#f3f3f4',
    ),
    'slots' => 
    array (
      'ink' => '#150c0f',
      'graphite' => '#24161b',
      'graphite-2' => '#342228',
      'paper' => '#f3f3f4',
      'paper-2' => '#e2e4e6',
      'surface' => '#ffffff',
      'line' => '#d2d4d9',
      'text' => '#1d1115',
      'muted' => '#785a64',
      'muted-light' => '#bbaab0',
      'accent' => '#8e2445',
      'accent-light' => '#c08497',
      'accent-ink' => '#8e2445',
      'on-accent' => '#ffffff',
      'field-line' => '#7f7a7f',
      'accent-card' => '#973654',
      'accent-muted' => '#e6cfd6',
      'accent-focus' => '#ffffff',
      'accent-hover' => '#eedee3',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'burnt-orange' => 
  array (
    'name' => 'Burnt Orange',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0f1113',
      1 => '#272b30',
      2 => '#e08a4c',
      3 => '#ebb38b',
      4 => '#f5f4f2',
    ),
    'slots' => 
    array (
      'ink' => '#0f1113',
      'graphite' => '#1a1d20',
      'graphite-2' => '#272b30',
      'paper' => '#f5f4f2',
      'paper-2' => '#e7e4e1',
      'surface' => '#ffffff',
      'line' => '#dbd6d1',
      'text' => '#14171a',
      'muted' => '#5d636a',
      'muted-light' => '#aeb2b7',
      'accent' => '#e08a4c',
      'accent-light' => '#ebb38b',
      'accent-ink' => '#885734',
      'on-accent' => '#0f1113',
      'field-line' => '#7b7a79',
      'accent-card' => '#cf8047',
      'accent-muted' => '#30241c',
      'accent-focus' => '#0f1113',
      'accent-hover' => '#2e231c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.42)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'alpine-silver' => 
  array (
    'name' => 'Alpine Silver',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#121416',
      1 => '#363b3f',
      2 => '#aab2bb',
      3 => '#c8cdd3',
      4 => '#f7f8f9',
    ),
    'slots' => 
    array (
      'ink' => '#121416',
      'graphite' => '#272b2f',
      'graphite-2' => '#363b3f',
      'paper' => '#f7f8f9',
      'paper-2' => '#eaecee',
      'surface' => '#ffffff',
      'line' => '#d6d9dd',
      'text' => '#181b1d',
      'muted' => '#60666c',
      'muted-light' => '#afb2b6',
      'accent' => '#aab2bb',
      'accent-light' => '#c8cdd3',
      'accent-ink' => '#61666c',
      'on-accent' => '#121416',
      'field-line' => '#7f8285',
      'accent-card' => '#9ea5ae',
      'accent-muted' => '#33373a',
      'accent-focus' => '#121416',
      'accent-hover' => '#292c2f',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.48)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'pearl-white' => 
  array (
    'name' => 'Pearl White',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#161513',
      1 => '#3c3935',
      2 => '#4a4038',
      3 => '#aaa5a1',
      4 => '#fbf9f6',
    ),
    'slots' => 
    array (
      'ink' => '#161513',
      'graphite' => '#2c2a26',
      'graphite-2' => '#3c3935',
      'paper' => '#fbf9f6',
      'paper-2' => '#f4efe7',
      'surface' => '#fefcfa',
      'line' => '#e7decd',
      'text' => '#1d1b19',
      'muted' => '#6d6a64',
      'muted-light' => '#b5b3b0',
      'accent' => '#4a4038',
      'accent-light' => '#aaa5a1',
      'accent-ink' => '#4a4038',
      'on-accent' => '#fefcfa',
      'field-line' => '#8a847a',
      'accent-card' => '#584f48',
      'accent-muted' => '#ccc7c4',
      'accent-focus' => '#fefcfa',
      'accent-hover' => '#e3e0dd',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'ivory-touring' => 
  array (
    'name' => 'Ivory Touring',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0a0f17',
      1 => '#1d2839',
      2 => '#27406b',
      3 => '#8694ac',
      4 => '#fbf8f2',
    ),
    'slots' => 
    array (
      'ink' => '#0a0f17',
      'graphite' => '#131b28',
      'graphite-2' => '#1d2839',
      'paper' => '#fbf8f2',
      'paper-2' => '#f4efde',
      'surface' => '#fefdfa',
      'line' => '#ece2c5',
      'text' => '#0e1520',
      'muted' => '#586a89',
      'muted-light' => '#a5afc0',
      'accent' => '#27406b',
      'accent-light' => '#8694ac',
      'accent-ink' => '#27406b',
      'on-accent' => '#fefdfa',
      'field-line' => '#868479',
      'accent-card' => '#384f76',
      'accent-muted' => '#bec4cf',
      'accent-focus' => '#fefdfa',
      'accent-hover' => '#dee1e5',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'moonstone' => 
  array (
    'name' => 'Moonstone',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#121316',
      1 => '#34343d',
      2 => '#a3a7c4',
      3 => '#c3c6d9',
      4 => '#f6f7f8',
    ),
    'slots' => 
    array (
      'ink' => '#121316',
      'graphite' => '#25262c',
      'graphite-2' => '#34343d',
      'paper' => '#f6f7f8',
      'paper-2' => '#e8e9ed',
      'surface' => '#ffffff',
      'line' => '#d4d5dd',
      'text' => '#18191d',
      'muted' => '#63646e',
      'muted-light' => '#afb0b6',
      'accent' => '#a3a7c4',
      'accent-light' => '#c3c6d9',
      'accent-ink' => '#606374',
      'on-accent' => '#121316',
      'field-line' => '#7e7f85',
      'accent-card' => '#979bb6',
      'accent-muted' => '#2f3139',
      'accent-focus' => '#121316',
      'accent-hover' => '#282930',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.46)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'chalk' => 
  array (
    'name' => 'Chalk',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#151514',
      1 => '#3a3a36',
      2 => '#34443c',
      3 => '#a6ada9',
      4 => '#f3f3f1',
    ),
    'slots' => 
    array (
      'ink' => '#151514',
      'graphite' => '#2a2a27',
      'graphite-2' => '#3a3a36',
      'paper' => '#f3f3f1',
      'paper-2' => '#e8e8e3',
      'surface' => '#ffffff',
      'line' => '#d9d9d3',
      'text' => '#1c1c1a',
      'muted' => '#63635f',
      'muted-light' => '#b4b4b1',
      'accent' => '#34443c',
      'accent-light' => '#a6ada9',
      'accent-ink' => '#34443c',
      'on-accent' => '#ffffff',
      'field-line' => '#7e7e7a',
      'accent-card' => '#44534c',
      'accent-muted' => '#c2c7c5',
      'accent-focus' => '#ffffff',
      'accent-hover' => '#e1e3e2',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'racing-yellow' => 
  array (
    'name' => 'Racing Yellow',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#101011',
      1 => '#2a2b2d',
      2 => '#e3b505',
      3 => '#edcf5c',
      4 => '#f3f3f4',
    ),
    'slots' => 
    array (
      'ink' => '#101011',
      'graphite' => '#1c1d1f',
      'graphite-2' => '#2a2b2d',
      'paper' => '#f3f3f4',
      'paper-2' => '#e3e4e5',
      'surface' => '#ffffff',
      'line' => '#d4d5d7',
      'text' => '#161718',
      'muted' => '#616366',
      'muted-light' => '#b1b2b4',
      'accent' => '#e3b505',
      'accent-light' => '#edcf5c',
      'accent-ink' => '#755f0b',
      'on-accent' => '#101011',
      'field-line' => '#797a7b',
      'accent-card' => '#d2a806',
      'accent-muted' => '#473b0e',
      'accent-focus' => '#101011',
      'accent-hover' => '#30290f',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.52)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'amethyst' => 
  array (
    'name' => 'Amethyst',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0f0c16',
      1 => '#292136',
      2 => '#6b4ca6',
      3 => '#9f8bc5',
      4 => '#f3f2f5',
    ),
    'slots' => 
    array (
      'ink' => '#0f0c16',
      'graphite' => '#1b1525',
      'graphite-2' => '#292136',
      'paper' => '#f3f2f5',
      'paper-2' => '#e3e0e8',
      'surface' => '#ffffff',
      'line' => '#d4d0db',
      'text' => '#15101e',
      'muted' => '#66597d',
      'muted-light' => '#b0a8bd',
      'accent' => '#6b4ca6',
      'accent-light' => '#9f8bc5',
      'accent-ink' => '#6b4ca6',
      'on-accent' => '#ffffff',
      'field-line' => '#7c7884',
      'accent-card' => '#775aad',
      'accent-muted' => '#f0edf6',
      'accent-focus' => '#ffffff',
      'accent-hover' => '#e9e4f2',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'chartreuse' => 
  array (
    'name' => 'Chartreuse',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#101112',
      1 => '#292c2d',
      2 => '#a3c13a',
      3 => '#c3d77f',
      4 => '#f3f4f4',
    ),
    'slots' => 
    array (
      'ink' => '#101112',
      'graphite' => '#1c1e1f',
      'graphite-2' => '#292c2d',
      'paper' => '#f3f4f4',
      'paper-2' => '#e3e5e5',
      'surface' => '#ffffff',
      'line' => '#d4d6d7',
      'text' => '#161718',
      'muted' => '#5e6264',
      'muted-light' => '#b0b3b5',
      'accent' => '#a3c13a',
      'accent-light' => '#c3d77f',
      'accent-ink' => '#5a6926',
      'on-accent' => '#101112',
      'field-line' => '#7d7e7f',
      'accent-card' => '#97b337',
      'accent-muted' => '#333b1c',
      'accent-focus' => '#101112',
      'accent-hover' => '#262b18',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.50)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'patina' => 
  array (
    'name' => 'Patina',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#15100c',
      1 => '#342b22',
      2 => '#7fa38f',
      3 => '#acc3b6',
      4 => '#f2f5f4',
    ),
    'slots' => 
    array (
      'ink' => '#15100c',
      'graphite' => '#241d16',
      'graphite-2' => '#342b22',
      'paper' => '#f2f5f4',
      'paper-2' => '#e0e9e4',
      'surface' => '#fbfdfc',
      'line' => '#cfdcd6',
      'text' => '#1d1711',
      'muted' => '#6f6053',
      'muted-light' => '#bbb2aa',
      'accent' => '#7fa38f',
      'accent-light' => '#acc3b6',
      'accent-ink' => '#55685b',
      'on-accent' => '#15100c',
      'field-line' => '#7a7d77',
      'accent-card' => '#779785',
      'accent-muted' => '#24251e',
      'accent-focus' => '#15100c',
      'accent-hover' => '#252620',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.40)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
  'aubergine' => 
  array (
    'name' => 'Aubergine',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#140b16',
      1 => '#332037',
      2 => '#b8b4c4',
      3 => '#d1ced9',
      4 => '#f4f2f5',
    ),
    'slots' => 
    array (
      'ink' => '#140b16',
      'graphite' => '#231426',
      'graphite-2' => '#332037',
      'paper' => '#f4f2f5',
      'paper-2' => '#e6e2e7',
      'surface' => '#ffffff',
      'line' => '#d8d1da',
      'text' => '#1c0f1f',
      'muted' => '#78577f',
      'muted-light' => '#baa7be',
      'accent' => '#b8b4c4',
      'accent-light' => '#d1ced9',
      'accent-ink' => '#66606d',
      'on-accent' => '#140b16',
      'field-line' => '#827884',
      'accent-card' => '#aba6b6',
      'accent-muted' => '#3f3743',
      'accent-focus' => '#140b16',
      'accent-hover' => '#2d2430',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.50)',
      1 => 'field-line: line darkened to a field boundary (push 0.46)',
    ),
  ),
  'vintage-mint' => 
  array (
    'name' => 'Vintage Mint',
    'default' => false,
    'selectable' => true,
    'colors' => 
    array (
      0 => '#0d1412',
      1 => '#24322f',
      2 => '#a8d5c2',
      3 => '#c6e4d7',
      4 => '#faf8f2',
    ),
    'slots' => 
    array (
      'ink' => '#0d1412',
      'graphite' => '#182320',
      'graphite-2' => '#24322f',
      'paper' => '#faf8f2',
      'paper-2' => '#f3eee0',
      'surface' => '#fefdfa',
      'line' => '#eae1c7',
      'text' => '#121c19',
      'muted' => '#566c66',
      'muted-light' => '#acb9b6',
      'accent' => '#a8d5c2',
      'accent-light' => '#c6e4d7',
      'accent-ink' => '#546d63',
      'on-accent' => '#0d1412',
      'field-line' => '#828273',
      'accent-card' => '#9cc6b4',
      'accent-muted' => '#3b4e47',
      'accent-focus' => '#0d1412',
      'accent-hover' => '#24312c',
    ),
    'sections' => 
    array (
      'dark' => true,
      'light' => true,
      'accent' => true,
    ),
    'notes' => 
    array (
      0 => 'accent-ink: accent darkened for text on light surfaces (push 0.54)',
      1 => 'field-line: line darkened to a field boundary (push 0.48)',
    ),
  ),
);
